// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwzzeajfavngycmbokcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3enplYWpmYXZuZ3ljbWJva2N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MzMxOTgsImV4cCI6MjA2OTMwOTE5OH0.i9oB2WWb85VW35b0ngNJSyFnkqtzUgIr90Iy2q29k0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});